#!/usr/bin/env bash

#/ command: golang:uninstall: "remove golang from the system"
#/ usage: rerun golang:uninstall  --shell-rc <> 
#/ rerun-variables: RERUN, RERUN_VERSION, RERUN_MODULES, RERUN_MODULE_DIR
#/ option-variables: SHELL_RC

. "$RERUN_MODULE_DIR/lib/functions.sh" "uninstall" || { 
  echo >&2 "Failed loading function library." ; exit 1 ; 
}

set -o errexit -o nounset -o pipefail

rerun_options_parse "$@"

# Command implementation
# ----------------------

sudo rm -rf /usr/local/go
sed -i '/^export PATH=\$PATH:\/usr\/local\/go\/bin:\$HOME\/go\/bin$/d' ${SHELL_RC}

# Done. Exit with last command exit status.
exit $?

