#!/usr/bin/env bash

#/ command: pdftk:merge: "merge pdf files"
#/ usage: rerun pdftk:merge  --input <> 
#/ rerun-variables: RERUN, RERUN_VERSION, RERUN_MODULES, RERUN_MODULE_DIR
#/ option-variables: INPUT

. "$RERUN_MODULE_DIR/lib/functions.sh" "merge" || { 
  echo >&2 "Failed loading function library." ; exit 1 ; 
}

set -o errexit -o nounset -o pipefail

rerun_options_parse "$@"

# Command implementation
# ----------------------

if ! command -v pdftk &> /dev/null; then
  rerun_die "pdftk not found"
fi

pdftk ${INPUT} cat output merged.pdf

# Done. Exit with last command exit status.
exit $?

