#!/usr/bin/env bash

#/ command: tokei:install: "install tokei in the system"
#/ usage: rerun tokei:install [options]
#/ rerun-variables: RERUN, RERUN_VERSION, RERUN_MODULES, RERUN_MODULE_DIR
#/ option-variables: 

. "$RERUN_MODULE_DIR/lib/functions.sh" "install" || { 
  echo >&2 "Failed loading function library." ; exit 1 ; 
}

set -o errexit -o nounset -o pipefail

rerun_options_parse "$@"

# Command implementation
# ----------------------

cargo install tokei

# Done. Exit with last command exit status.
exit $?

