#!/usr/bin/env bash

#/ command: aliases:uninstall: "uninstall aliases in the system"
#/ usage: rerun aliases:uninstall [options]
#/ rerun-variables: RERUN, RERUN_VERSION, RERUN_MODULES, RERUN_MODULE_DIR
#/ option-variables: 

. "$RERUN_MODULE_DIR/lib/functions.sh" "uninstall" || { 
  echo >&2 "Failed loading function library." ; exit 1 ; 
}

set -o errexit -o nounset -o pipefail

rerun_options_parse "$@"

# Command implementation
# ----------------------

if [ ! -f ~/.aliases ]; then
  rerun_die "~/.aliases not found" 
fi

rm ~/.aliases

# Done. Exit with last command exit status.
exit $?

