#!/usr/bin/env bash

#/ command: obsidian:install: "install obsidian in the system"
#/ usage: rerun obsidian:install  --version <> 
#/ rerun-variables: RERUN, RERUN_VERSION, RERUN_MODULES, RERUN_MODULE_DIR
#/ option-variables: VERSION

. "$RERUN_MODULE_DIR/lib/functions.sh" "install" || { 
  echo >&2 "Failed loading function library." ; exit 1 ; 
}

set -o errexit -o nounset -o pipefail

rerun_options_parse "$@"

# Command implementation
# ----------------------

TEMP_DIR=$(mktemp -d)
cd ${TEMP_DIR}

PACKAGE_NAME=obsidian_${VERSION}_amd64.deb

wget https://github.com/obsidianmd/obsidian-releases/releases/download/v${VERSION}/${PACKAGE_NAME}
sudo apt install ./${PACKAGE_NAME}

rm -r ${TEMP_DIR}

# Done. Exit with last command exit status.
exit $?

