#!/usr/bin/env bash

#/ command: dropbox:txtmd: "merge txt files into md by title"
#/ usage: rerun dropbox:txtmd [options]
#/ rerun-variables: RERUN, RERUN_VERSION, RERUN_MODULES, RERUN_MODULE_DIR
#/ option-variables: 

. "$RERUN_MODULE_DIR/lib/functions.sh" "txtmd" || { 
  echo >&2 "Failed loading function library." ; exit 1 ; 
}

set -o errexit -o nounset -o pipefail

rerun_options_parse "$@"

# Command implementation
# ----------------------

find . -iname "*.txt" -exec sh -c '
  FILEPATH="$0"
  FILENAME=$(basename "${FILEPATH}")
  DIRNAME=$(dirname "${FILEPATH}")
  TITLE=${FILENAME%.*}
  TITLE=${TITLE% ([0-9]*)}

  if ! [ -f "${DIRNAME}/${TITLE}.md" ]; then
    mv "${FILEPATH}" "${DIRNAME}/${TITLE}.md"
    exit 0
  fi

  cat "${FILEPATH}" | tail -n +2 >> "${DIRNAME}/${TITLE}.md"
  rm "${FILEPATH}"
' "{}" \;

# Done. Exit with last command exit status.
exit $?

